blog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import DispatchListView, DispatchCreateView, DispatchDetailView, DispatchUpdateView, \
    DispatchDeleteView, AttemptsListView, ClientListView, MessageListView, ClientDetailView, ClientUpdateView, \
    ClientCreateView, ClientDeleteView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    index

app_name = MailingConfig.name

urlpatterns = [
    path('', index, name='home'),
    path('dispatches/', DispatchListView.as_view(), name='dispatch_list'),
    path('dispatch/attempts/', cache_page(60)(AttemptsListView.as_view()), name='attempts_list'),
    path('dispatch/create/', DispatchCreateView.as_view(), name='dispatch_create'),
    path('dispatch/<int:pk>/', DispatchDetailView.as_view(), name='dispatch_detail'),
    path('dispatch/edit/<int:pk>/', DispatchUpdateView.as_view(), name='dispatch_update'),
    path('dispatch/delete/<int:pk>/', DispatchDeleteView.as_view(), name='dispatch_delete'),
    path('clients/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/edit/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
]

mailing/models.py
from datetime import datetime
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Клиент"""

    email = models.EmailField(verbose_name='почта', unique=True)
    name = models.CharField(max_length=150, verbose_name='имя')
    surname = models.CharField(max_length=150, verbose_name='фамилия')
    comments = models.TextField(verbose_name='коментарий', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Создатель', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.surname}, почта:{self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('name', 'surname')


class Message(models.Model):
    """Сообщение рассылки"""

    topic_message = models.CharField(max_length=100, verbose_name='тема сообщения')
    title_message = models.CharField(max_length=100, verbose_name='заголовок')
    body_message = models.TextField(verbose_name='сообщение')
    owner = models.ForeignKey(User, verbose_name='Создатель', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title_message

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('title_message', 'topic_message')


class Dispatch(models.Model):
    """Рассылка"""

    DAILY = 'раз в день'
    WEEKLY = 'раз в неделю'
    MONTHLY = 'раз в месяц'

    CREATED = 'создана'
    LAUNCHED = 'запущена'
    CANCELLED = 'отменена'
    COMPLETED = 'завершена'
    DELETED = 'удалена'

    PERIODICITY_CHOICES = [
        (DAILY, 'раз в день'),
        (WEEKLY, 'раз в неделю'),
        (MONTHLY, 'раз в месяц')
    ]

    STATUS_CHOICES = [
        (CREATED, 'создана'),
        (LAUNCHED, 'запущена'),
        (CANCELLED, 'отменена'),
        (COMPLETED, 'завершена'),
    ]

    title = models.CharField(max_length=100, verbose_name='заголовок', **NULLABLE)
    first_sent_date_time = models.DateTimeField(verbose_name='дата и время первой отправки')
    next_sent_date_time = models.DateTimeField(default=None, verbose_name='дата и время следующей отправки', **NULLABLE, editable=False,)
    last_sent_date_time = models.DateTimeField(default=None, verbose_name='дата и время последней отправки')
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, verbose_name='периодичность')
    status = models.CharField(default=CREATED, max_length=20, choices=STATUS_CHOICES, verbose_name='статус')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение', related_name='dispatch')
    clients = models.ManyToManyField(Client, verbose_name='клиенты', related_name='dispatch')
    is_activ = models.BooleanField(default=True, verbose_name='Активна')
    owner = models.ForeignKey(User, verbose_name='Создатель', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('title', 'first_sent_date_time', 'status',)
        permissions = [
            ('can_edit_status', 'Can edit status'),
            ('can_edit_is_activ', 'Can edit is activ')
        ]


class Attempts(models.Model):
    """Попытка рассылки"""

    datetime = models.DateTimeField(verbose_name='дата и время последней отправки')
    status = models.BooleanField(default=True, verbose_name='успешно')
    dispatch = models.ForeignKey(Dispatch, on_delete=models.CASCADE, verbose_name='рассылка', related_name='attempts')
    mail_response = models.CharField(max_length=100, verbose_name='ответ почтового сервиса', **NULLABLE)

    def __str__(self):
        return f'Отправка {self.dispatch} : {self.datetime}'

    class Meta:
        verbose_name = 'Попытка отправки'
        verbose_name_plural = 'Попытки отправки'
        ordering = ('datetime', 'status', 'dispatch',)

mailing/forms.py
from django.forms import ModelForm, BooleanField

from mailing.models import Dispatch, Client, Message


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class DispatchForm(ModelForm):
    class Meta:
        model = Dispatch
        exclude = ('next_sent_date_time', 'owner', )


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ('owner', )


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ('owner', )

mailing/views.py
import random
from urllib import request

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import DispatchForm, ClientForm, MessageForm
from mailing.models import Dispatch, Client, Attempts, Message
from mailing.services import send_mailing


class DispatchListView(ListView):
    """Список рассылок"""

    model = Dispatch

    def get_context_data(self, **kwargs):
        context = super(DispatchListView, self).get_context_data(**kwargs)
        mailings = Dispatch.objects.filter(status='завершена')
        context['dispatch_completed'] = mailings
        return context


class DispatchCreateView(CreateView, LoginRequiredMixin):
    """Создание новой рассылки"""

    model = Dispatch
    form_class = DispatchForm
    success_url = reverse_lazy('mailing:dispatch_list')

    def form_valid(self, form):
        """Присваивание владельца при создании рассылки"""

        dispatch = form.save()
        user = self.request.user
        dispatch.owner = user
        dispatch.save()
        return super().form_valid(form)


class DispatchDetailView(DetailView):
    """Просмотр рассылки"""

    model = Dispatch

    def get_context_data(self, **kwargs):
        context = super(DispatchDetailView, self).get_context_data(**kwargs)
        context['clients'] = Client.objects.filter(dispatch=self.object)
        return context


class DispatchUpdateView(UpdateView, LoginRequiredMixin):
    """Изменение рассылки"""

    model = Dispatch
    form_class = DispatchForm

    def get_success_url(self):
        return reverse('mailing:dispatch_list')

        # return reverse('mailing:dispatch_list', args=[self.kwargs.get('pk')])


class DispatchDeleteView(DeleteView, LoginRequiredMixin):
    """Удаление рассылки"""

    model = Dispatch
    success_url = reverse_lazy('mailing:dispatch_list')


class AttemptsListView(ListView):
    """Отчет проведенных рассылок"""

    model = Attempts


class ClientListView(ListView):
    """Список клиентов"""

    model = Client

    def get_context_data(self, *args, **kwargs):
        """Выводит пользователю список клиентов, создателем которых он является"""

        context_data = super().get_context_data(*args, **kwargs)
        # products = get_product_from_cache()
        clients = Client.objects.filter(owner=self.request.user)
        context_data['object_list'] = clients
        return context_data


class ClientDetailView(DetailView):
    """Просмотр клиента"""

    model = Client


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    """Изменение клиента"""

    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing:client_list')


class ClientCreateView(CreateView, LoginRequiredMixin):
    """Создание нового клиента"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """Присваивание владельца при создании клиента """

        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientDeleteView(DeleteView, LoginRequiredMixin):
    """Удаление клиента"""

    model = Client
    success_url = reverse_lazy('mailing:client_list')


class MessageListView(ListView):
    """Список сообщений"""

    model = Message

    def get_context_data(self, *args, **kwargs):
        """Выводит пользователю список сообщений, создателем которых он является"""

        context_data = super().get_context_data(*args, **kwargs)
        # products = get_product_from_cache()
        messages = Message.objects.filter(owner=self.request.user)
        context_data['object_list'] = messages
        return context_data


class MessageCreateView(CreateView, LoginRequiredMixin):
    """Создание нового сообщения"""

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """Присваивание владельца при создании сообщения"""

        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class MessageDetailView(DetailView):
    """Просмотр сообщения"""
    model = Message


class MessageUpdateView(UpdateView, LoginRequiredMixin):
    """Изменение клиента"""

    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailing:message_list')


class MessageDeleteView(DeleteView, LoginRequiredMixin):
    """Удаление клиента"""

    model = Message
    success_url = reverse_lazy('mailing:message_list')


def index(request):
    count_mailin_all = len(Dispatch.objects.all())
    count_mailin_activ = len(Dispatch.objects.filter(is_activ=True))
    count_client_list = len(Client.objects.all())
    blogs = Blog.objects.all()
    blog_list = list(blogs)
    if len(blog_list) >= 3:
        rand_blog = random.sample(blog_list, 3)
    else:
        rand_blog = blog_list
    context = {
        'count_mailing_all': count_mailin_all,
        'count_mailing': count_mailin_activ,
        'count_clients': count_client_list,
        'blog_list': rand_blog
    }
    return render(request, "mailing/home.html", context)

mailing/templates/mailing/attempts_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Проведенные рассылки</h1>
            </div>
        </div>
    </section>


    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for attempt in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Рассылка {{ attempt.dispatch }}</h4>
                            <h8 class="my-0 font-weight-normal">Результат рассылки:
                                {% if attempt.status %}
                                Успешно
                                {% else %}
                                Неуспешно
                                {% endif %}
                            </h8>
                            <p class="my-0 font-weight-normal">Дата и время последней отправки рассылки: {{ attempt.datetime }}</p>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ dispatch.message|slice:100 }}</p>
                            <small class="text-body-secondary">{{ dispatch.status }}</small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <section class="py-5 text-center container">
        <a class="btn btn-primary" href="{% url 'mailing:dispatch_list'%}" role="button">Назад</a>
    </section>


</main>
{% endblock %}

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="coll-12">
        <div class="coll-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{object.name}} {{object.surname}} - {{object.email}}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-warning"> Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h6 class="my-0 font-weight-normal">Имя: {{ object.name }} {{ object.surname }}</h6>
            <h5 class="my-0 font-weight-normal">Почта: {{ object.email }} </h5>
        </div>

        <div class="card-body">

            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>Коментарий: {{object.comments}}</li>
            </ul>
            <a class="btn btn-primary" href="{% url 'mailing:client_update' client.pk %}" role="button">Редактировать</a>
            <a class="btn btn-danger" href="{% url 'mailing:client_delete' client.pk %}" role="button">Удалить</a>
        </div>
        <a class="btn btn-primary" href="{% url 'mailing:client_list'%}" role="button">Назад</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                {% if object_list %}
                <h1 class="fw-light">Список клиентов</h1>
                {% else %}
                <h3 class="fw-light">Ваш список клиентов пуст</h3>
                {% endif %}
                <p>
                    <a class="btn btn-primary my-2" href="{% url 'mailing:client_create' %}">Создать клиента</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for client in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Имя: {{ client.name }} {{ client.surname }}</h4>
                            <h8 class="my-0 font-weight-normal">Почта: {{ client.email }}</h8>
                        </div>
                        <div class="card-body">
                            <small class="text-body-secondary">{{ client.comments }}</small>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mailing:client_detail' client.pk %}"
                   role="button">Посмотреть</a>
                                    <a class="btn btn-success" href="{% url 'mailing:client_update' client.pk %}"
                   role="button">Редактировать</a>
                                    <a class="btn btn-danger" href="{% url 'mailing:client_delete' client.pk %}"
                   role="button">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/dispatch_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="coll-12">
        <div class="coll-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{object.title}}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'mailing:dispatch_list' %}" class="btn btn-warning"> Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/dispatch_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>

        <div class="card-body">

            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                {% for client in  clients %}
                <p>{{ client.email }}<p>
                {% endfor %}
            </ul>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>Первая отправка: {{object.first_sent_date_time}}</li>
                <li>Следующая отправка: {{object.next_sent_date_time}}</li>
                <li>Последняя отправка: {{object.last_sent_date_time}}</li>
            </ul>

            <ul class="list-unstyled mt-3 mb-4 text-start m-3">

                <li>{{ object.message|slice:100 }}</li>
                <li>{{ object.status }}</li>
            </ul>
            {% if user == dispatch.owner %}
            <a class="btn btn-primary" href="{% url 'mailing:dispatch_update' dispatch.pk %}" role="button">Редактировать</a>
            {% endif %}
            <a class="btn btn-primary" href="{% url 'mailing:dispatch_list'%}" role="button">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/dispatch_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row">
                <!--enctype="multipart/form-data" необходимо прописывать чтобы была возможность загружать не только текст но и файлы>-->
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% if object %}
                                Редактирование рассылки
                                {% else %}
                                Создание рассылки
                                {% endif%}
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
                {% if object %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                            <hr>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/dispatch_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Сервис рассылок</h1>
                {% if user.is_authenticated %}
                <p>
                    <a class="btn btn-primary my-2" href="{% url 'mailing:dispatch_create' %}" >Создать рассылку</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for dispatch in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ dispatch.title }}</h4>
                            <h8 class="my-0 font-weight-normal">Периодичность: {{ dispatch.periodicity }}</h8>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ dispatch.message|slice:100 }}</p>
                            <small class="text-body-secondary">{{ dispatch.status }}</small>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mailing:dispatch_detail' dispatch.pk %}"
                   role="button">Посмотреть</a>
                                    {% if user == dispatch.owner %}
                                    <a class="btn btn-success" href="{% url 'mailing:dispatch_update' dispatch.pk %}"
                   role="button">Редактировать</a>
                                    <a class="btn btn-danger" href="{% url 'mailing:dispatch_delete' dispatch.pk %}"
                   role="button">Удалить</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Главная страница сервиса</h1>
                {% if user.is_authenticated %}
                <p>
                    <a class="btn btn-primary my-2" href="{% url 'mailing:dispatch_list' %}">Рассылки</a>
                    <a class="btn btn-primary my-2" href="{% url 'mailing:message_list' %}">Сообщения</a>
                    <a class="btn btn-primary my-2" href="{% url 'mailing:client_list' %}">Клиенты</a>
                    <a class="btn btn-primary my-2" href="{% url 'blog:blog_list' %}">Блог</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>
    <ul class="list-group">
  <li class="list-group-item">Всего рассылок: {{count_mailing_all}}</li>
  <li class="list-group-item">Активных рассылок: {{count_mailing}}</li>
  <li class="list-group-item">Всего клиентов: {{count_clients}}</li>
</ul>
    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for blog in blog_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ blog.content|slice:100 }}</p>
                            <small class="text-body-secondary">Количество просмотров: {{ blog.views_count }}</small>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk %}"
                   role="button">Посмотреть</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h5 class="my-0 font-weight-normal">Тема: {{ object.topic_message }}</h5>
            <h4 class="my-0 font-weight-normal">Заголовок: {{ object.title_message }}</h4>
        </div>

        <div class="card-body">

            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.body_message }}</li>
            </ul>
            <a class="btn btn-primary" href="{% url 'mailing:message_update' message.pk %}" role="button">Редактировать</a>
            <a class="btn btn-danger" href="{% url 'mailing:message_delete' message.pk %}" role="button">Удалить</a>
        </div>
        <a class="btn btn-primary" href="{% url 'mailing:message_list'%}" role="button">Назад</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                {% if object_list %}
                <h1 class="fw-light">Ваши сообщения</h1>
                {% else %}
                <h3 class="fw-light">У вас нет сообщений</h3>
                {% endif %}
                <p>
                    <a class="btn btn-primary my-2" href="{% url 'mailing:message_create' %}">Создать сообщение</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for message in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Тема: {{ message.topic_message }}</h4>
                            <h8 class="my-0 font-weight-normal"> {{ message.title_message }}</h8>
                        </div>
                        <div class="card-body">
                            <small class="text-body-secondary">{{ message.body_message|slice:100 }}</small>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mailing:message_detail' message.pk %}"
                   role="button">Посмотреть</a>
                                    <a class="btn btn-success" href="{% url 'mailing:message_update' message.pk %}"
                   role="button">Редактировать</a>
                                    <a class="btn btn-danger" href="{% url 'mailing:message_delete' message.pk %}"
                   role="button">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}