blog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    # slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    picture = models.ImageField(upload_to='catalog/blog/picture', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликованно')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    owner = models.ForeignKey(User, verbose_name='Автор', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('title', 'content')
        permissions = [
            ('can_edit_published', 'Can edit is_published'),
        ]

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        exclude = ('owner', 'views_count')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import ModelForm
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView, LoginRequiredMixin):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """выводит только опубликованные блоги"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView, LoginRequiredMixin):
    """Создание новой статьи"""
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        """Присваивание владельца при создании статьи"""

        user = self.request.user
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.owner = user
            new_blog.save()

        return super().form_valid(form)


class BlogDetailView(DetailView, LoginRequiredMixin):
    """Просмотр статьи"""

    model = Blog

    def get_object(self, queryset=None):
        """Cчетчик просмотров статьи"""

        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    """Изменение статьи"""

    model = Blog
    form_class = BlogForm

    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView, LoginRequiredMixin):
    """Удаление статьи"""

    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="coll-12">
        <div class="coll-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью? "{{object.title}}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning"> Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <img class="card-img-top" src="/media/{{ object.picture }}">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.content }}</li>
            </ul>
            {% if user == object.owner %}
            <a class="btn btn-primary" href="{% url 'blog:blog_update' object.pk %}" role="button">Редактировать</a>
            <a class="btn btn-danger" href="{% url 'blog:blog_delete' object.pk %}" role="button">Удалить</a>
            {% endif %}
        </div>
        <div class="card-footer">
            Просмотры {{object.views_count}}
        </div>

    </div>
    <a class="btn btn-primary" href="{% url 'blog:blog_list'%}" role="button">Назад</a>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Блог</h1>
                {% if user.is_authenticated %}
                <p>
                    <a class="btn btn-primary my-2" href="{% url 'blog:blog_create' %}">Создать статью</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for blog in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ blog.content|slice:100 }}</p>
                            <small class="text-body-secondary">Количество просмотров: {{ blog.views_count }}</small>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk %}"
                   role="button">Посмотреть</a>
                                    {% if user == blog.owner %}
                                    <a class="btn btn-success" href="{% url 'blog:blog_update' blog.pk %}"
                   role="button">Редактировать</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}